### PR TITLE
Peelanalyser show report

### PR DESCRIPTION
**Pull request by Fabsi110**
This is a enhanced version of the extension peel-analyser. Main new features are:
 - added a Windows batch file for windows users (very basic, just calls java and adds the jars to classpath, if there is demand, I'll build better error handling in future)
 - median time of ExperimentRuns added
 - integrated the peel-analyser into the peel-dist folder
 - refactoring
 - a updated sample Experiment

### CODE REVIEW

**Comment by aalexandrov** [comment]
@Fabsi110 nice additions! Can we get rid of the "merge" commits and squash the remaining so we have one commit per feature, e.g.:

- [ ] Added a Windows batch file for windows users.
- [ ] Added median time of ExperimentRuns.
- [ ] Integrated peel-analyser in the peel-dist folder.
- [ ] Refactored ... (say what you have refactored)
- [ ] Updated sample Experiment.

**Comment by akunft** [comment]
@Fabsi110 pls rebase to the current master, as the rebase of #22 introduced some changes in the history

**Comment by Fabsi110** [comment]
I rebased to current master and I changed the code a little bit so that it will work with older versions of Spark again...
I also squashed some commits to logically ones... But somehow I don't even see the Merge commits when I want to squash them too...

**Comment by akunft** [comment]
@Fabsi110 so i rebased your commits to the current master. You can find it in branch stratosphere/analyser_show_report. Can you squash your commits in this branch and use it for your PR?

**Comment by Fabsi110** [comment]
Thanks @akunft for the rebase. I used your branch, squashed some of the commits and made a force push into my branch, so the PR should be up-todate.
I am unfamiliar to the process of rebasing. When I look into the comparison I see that the branch is now 51 commits behind master. How does that come?

**Comment by aalexandrov** [comment]
@Fabsi110 based on [what I can see here](https://github.com/stratosphere/peel/network) your branch (or at least a substantial part of it) already got rebased and merged into the master. 

For some reason the version the `peelanalyser_show_report` branch that @akunft pushed to the main repository is quite different than the current master and contains duplicate commits.

You might try

```bash
git rebase master
```

to check whether this solves the issue with some advanced merging scheme, but I am not willing to bet money on that.

A somewhat more manual and issue-proof strategy is to do the following:

- [ ] create a new branch 'feature_rebased' forking from the current master
- [ ] cherry-pick everything from `peelanalyser_showReport` which is newer than [this commit](https://github.com/stratosphere/peel/commit/41552e7e4cdb0b371281bdbca14d4691e51579df) onto `feature_rebased`.
- [ ] move `peelanalyser_showReport` to another name (for backup)
- [ ] rename `feature_rebased` to `peelanalyser_showReport` and force-push.

**Comment by Fabsi110** [comment]
So I read a bit about rebasing and the differences to merging and I believe this is what happened:
In early January I was ready with the foundations of my code, the main functionality was in place and I created a pull request (#24) to get it into the master.
It wasn't merged for a long while and I decided to add new features to it, so I created a new branch from that one, called peelanalyser_showReport (because I needed the features, but I didn't want to add unready code to my PR). I worked on this one later on and added features to it and some commits. 
In May @akunft merged my old pull request from January, but he didn't just merged it, but rebased it to the master. As I understand it rebasing changes the commits, so every commits received a new hash. The new branch peelanalyser_showReport had the old commits with old hashes. So when I made my pull request for this branch it actually had the very same commits all over again, the names and everything is exactly the same, but the hashes are different. That's why my pull request has duplicate commits to the master and that is why the rebasing of @akunft in branch analyser_show_Report didn't worked as expected...
So what I'm now trying to do is to use the strategy @aalexandrov proposed here. So let's see ;) As a backup I created the branch peelanalyser_showReport_old from the old local repository on my laptop (which still contains all duplicates, but is clean in the history).

**Comment by aalexandrov** [comment]
As I said, because the contents of the commits is more or less unchanged even after @akunt's rebasing, you should be able to find a subsequence in the two branches that contains exactly the same diffs (even though they are now with different IDs). 

Long story short, if this is the case you only have to "append" the extra commits from your feature branch onto the current master and make a PR (ideally the old one, and this could be achieved by force pushing into the same branch name once you're done).

**Comment by Fabsi110** [comment]
Okay, so I cherry-picked every new commits and made a force push into this branch. This branch should be up to date... Thanks for the help @aalexandrov

**Comment by aalexandrov** [comment]
:clap: :clap: :clap:

**Pull request merged**
